LIB_CPPFLAGS = @LIB_CPPFLAGS@
SETEGID = 
GAMEDATA_IN_LIB = false
LIBDIR = ${libdir}
libdatadir = /usr/local/share/angband/
vardatadir = /usr/local/var/games/angband/
varshareddatadir = /usr/local/var/games/angband/user/
docdatadir = /usr/local/share/doc/angband/
configdir = /usr/local/etc/angband/
pdfdir ?= ${docdir}
ECHO_N ?= -n
bindir ?= /usr/local/games
dvidir ?= ${docdir}
datadir ?= ${datarootdir}
CPPFLAGS ?=  -DHAVE_CONFIG_H -I. -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 
SHELL ?= /bin/bash
program_transform_name ?= s,x,x,
DEFS ?= -DHAVE_CONFIG_H
infodir ?= ${datarootdir}/info
libexecdir ?= ${exec_prefix}/libexec
localedir ?= ${datarootdir}/locale
LTLIBOBJS ?= 
LDFLAGS ?= 
includedir ?= ${prefix}/include
libdir ?= ${exec_prefix}/lib
localstatedir ?= ${prefix}/var
docdir ?= ${prefix}/share/doc/angband
INSTALL_SCRIPT ?= ${INSTALL}
MV ?= /usr/bin/mv
GLIB_LIBS ?= @GLIB_LIBS@
sharedstatedir ?= ${prefix}/com
OBJEXT ?= o
PKG_CONFIG ?= @PKG_CONFIG@
sysconfdir ?= ${prefix}/etc
htmldir ?= ${docdir}
PACKAGE_STRING ?= Angband 4.2.6
sbindir ?= ${exec_prefix}/sbin
CP ?= /usr/bin/cp
SET_MAKE ?= 
ECHO_C ?= 
psdir ?= ${docdir}
oldincludedir ?= /usr/include
mandir ?= ${datarootdir}/man
PACKAGE_NAME ?= Angband
ECHO_T ?= 
LIBOBJS ?= 
ac_ct_CC ?= cc
PACKAGE_VERSION ?= 4.2.6
LN_S ?= ln -s
GREP ?= @GREP@
INSTALL_DATA ?= ${INSTALL} -m 644
datarootdir ?= ${prefix}/share
RM ?= /usr/bin/rm
INSTALL_PROGRAM ?= ${INSTALL}
exec_prefix ?= /usr/local
EGREP ?= @EGREP@
prefix ?= /usr/local
VERSION ?= @VERSION@
MAINFILES = $(BASEMAINFILES) $(GCUMAINFILES) $(X11MAINFILES) $(SPOILMAINFILES)
TEST_LIBS = 
TEST_WORKING_DIRECTORY ?= /home/matt3r/calculator-files/angband
USE_STATS = 
SPHINXBUILD ?= 
DOC_HTML_THEME ?= 
NOINSTALL = 
CROSS_COMPILE = no
ENABLESDL = no
ENABLESDL2 = no
ENABLEWIN = no
ENABLEX11 = yes
